# Generated by Django 4.1.7 on 2024-07-08 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("jobapp", "0001_initial"),
        ("users", "0001_initial"),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobposts",
                to="users.employer",
            ),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="major_skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="major_skill",
                to="common.skill",
            ),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="qualification",
            field=models.ManyToManyField(to="common.qualification"),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="skills",
            field=models.ManyToManyField(to="common.skill"),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="job_post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="jobapp.jobpost"
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.jobseeker",
            ),
        ),
    ]
