version: "3.9"

services:
    api: &api
        build:
            context: .
            dockerfile: ./docker/production/django/Dockerfile
        command: /start
        image: jobportal
        volumes:
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        env_file:
            - ./.envs/.production/.django
            - ./.envs/.production/.postgres
        depends_on:
            - postgres
            - redis
        networks:
            - reverseproxy_nw

    postgres:
        build:
            context: .
            dockerfile: ./docker/production/postgres/Dockerfile
        image: jobportal_database
        volumes:
            - production_postgres_data:/var/lib/postgresql/data
            - production_postgres_data_backups:/backups
        env_file:
            - ./.envs/.production/.postgres
        networks:
            - reverseproxy_nw

    redis:
        image: redis:7-alpine
        networks:
            - reverseproxy_nw

    celery_worker:
        <<: *api
        image: jobportal_celery_worker
        command: /start-celeryworker
        networks:
            - reverseproxy_nw

    flower:
        <<: *api
        image: jobportal_flower
        command: /start-flower
        volumes:
            - flower_data:/data
        networks:
            - reverseproxy_nw

networks:
    reverseproxy_nw:
        external: true

volumes:
    static_volume: {}
    media_volume: {}
    production_postgres_data: {}
    production_postgres_data_backups: {}
    flower_data: {}
