#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

working_dir="$(dirname ${0})"

source "${working_dir}/_sourced/constants.sh"
source "${working_dir}/_sourced/messages.sh"

message_welcome "Backing up the '${MYSQL_DATABASE}' database..."

if [[ "${MYSQL_USER}" == "root" ]]; then
  message_error "Backing up as 'root' user is not allowed. Assign 'MYSQL_USER' env with another one and try again."
  exit 1
fi

export MYSQL_PWD="${MYSQL_PASSWORD}"

backup_filename="${BACKUP_FILE_PREFIX}_$(date +'%Y_%m_%dT%H_%M_%S').sql.gz"

mysqldump -h"${MYSQL_HOST}" -P"${MYSQL_PORT}" -u"${MYSQL_USER}" "${MYSQL_DATABASE}" | gzip > "${BACKUP_DIR_PATH}/${backup_filename}"

message_success "'${MYSQL_DATABASE}' database backup '${backup_filename}' has been created successfully and placed in '${BACKUP_DIR_PATH}'"